1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?


In [6]:
#solution to 5
string="The quick' brown! fox, jumps; over lazy dogs!"
#make a list of all special characters , if any of the characters in string matches with one found in the list, replace it with blank. 
punctuation_list=["'", ",", "!", ";"]
for i in punctuation_list:
    if i in string:
        string= string.replace(i," ")
print(string)
    

The quick  brown  fox  jumps  over lazy dogs 


In [26]:
#solution to 4
string="The quick brown fox jumps over lazy dogs."
string=string.lower()
sorted_string=sorted(string.split())
print(sorted_string)


['brown', 'dogs.', 'fox', 'jumps', 'lazy', 'over', 'quick', 'the']


In [8]:
#solution to 3
import numpy as np
a=[[1,2,3],[4,4,5],[6,7,8]]
mat1=np.mat(data=a)
matt=np.transpose(mat1)
print(mat1)
print(matt)

[[1 2 3]
 [4 4 5]
 [6 7 8]]
[[1 4 6]
 [2 4 7]
 [3 5 8]]


In [5]:
#solution to 2
import numpy as np
a=[[1,2,3],[4,4,5],[6,7,8]]
mat1=np.mat(data=a)
print(mat1)
b=[[2,3,3],[5,0,0],[6,78,6]]
mat2= np.mat(b)
print(np.dot(mat1,mat2))


[[1 2 3]
 [4 4 5]
 [6 7 8]]
[[ 30 237  21]
 [ 58 402  42]
 [ 95 642  66]]


In [6]:
#solution to 1
import numpy as np
a=[[1,2,3],[4,4,5],[6,7,8]]
mat1=np.mat(data=a)
print(mat1)
b=[[2,3,3],[5,0,0],[6,78,6]]
mat2= np.mat(b)
print(mat1 +mat2)


[[1 2 3]
 [4 4 5]
 [6 7 8]]
[[ 3  5  6]
 [ 9  4  5]
 [12 85 14]]
